name: Civil Services - City Council Data for Philadelphia, PA
description: This project provides the City Council Data, Headshots & City Photo for Philadelphia, PA ( JSON, XML, CSV, SQL & YML formats )
theme: jekyll-theme-cayman